In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#%pip install keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.metrics import confusion_matrix, precision_score
from sklearn.metrics import recall_score, f1_score, accuracy_score

In [85]:
df = pd.read_csv('final_df.csv')
df.head()

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,grid,podium,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
0,1983,1,False,False,True,False,False,keke_rosberg,1,15,...,0,0,0,0,0,0,0,0,0,1
1,1983,1,False,False,True,False,False,prost,2,6,...,0,0,0,1,0,0,0,0,0,0
2,1983,1,False,False,True,False,False,tambay,3,4,...,0,0,0,0,0,0,0,0,0,0
3,1983,1,False,False,True,False,False,piquet,4,1,...,0,0,0,0,0,0,0,0,0,0
4,1983,1,False,False,True,False,False,warwick,5,7,...,0,0,0,0,0,0,0,0,0,0

In [86]:
df

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,grid,podium,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
0,1983,1,False,False,True,False,False,keke_rosberg,1,15,...,0,0,0,0,0,0,0,0,0,1
1,1983,1,False,False,True,False,False,prost,2,6,...,0,0,0,1,0,0,0,0,0,0
2,1983,1,False,False,True,False,False,tambay,3,4,...,0,0,0,0,0,0,0,0,0,0
3,1983,1,False,False,True,False,False,piquet,4,1,...,0,0,0,0,0,0,0,0,0,0
4,1983,1,False,False,True,False,False,warwick,5,7,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14268,2019,21,True,False,False,False,False,giovinazzi,16,16,...,0,0,0,0,0,0,0,0,0,0
14269,2019,21,True,False,False,False,False,raikkonen,17,13,...,0,0,0,0,0,0,0,0,0,0
14270,2019,21,True,False,False,False,False,russell,18,17,...,0,0,0,0,0,0,0,0,0,1
14271,2019,21,True,False,False,False,False,kubica,19,19,...,0,0,0,0,0,0,0,0,0,1
14272,2019,21,True,False,False,False,False,bottas,20,4,...,0,0,0,0,0,0,0,0,0,0

In [87]:
df2 = df.copy()
df2.podium = df2.podium.map(lambda x: 1 if x == 1 else 0)

train = df2[df2.season <2019]
X_train = train.drop(['driver', 'podium'], axis = 1)
y_train = train.podium

scaler = StandardScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)

In [88]:
X_train

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,grid,driver_points,driver_wins,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
0,-1.647324,-1.609257,-0.860053,-0.153859,1.811523,-0.338102,-0.362729,-1.609286,-0.465586,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,3.209945
1,-1.647324,-1.609257,-0.860053,-0.153859,1.811523,-0.338102,-0.362729,-1.461131,-0.465586,-0.310681,...,-0.216773,-0.109343,-0.194304,4.913933,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,-0.311532
2,-1.647324,-1.609257,-0.860053,-0.153859,1.811523,-0.338102,-0.362729,-1.312976,-0.465586,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,-0.311532
3,-1.647324,-1.609257,-0.860053,-0.153859,1.811523,-0.338102,-0.362729,-1.164821,-0.465586,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,-0.311532
4,-1.647324,-1.609257,-0.860053,-0.153859,1.811523,-0.338102,-0.362729,-1.016666,-0.465586,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,-0.311532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13876,1.666223,2.321984,-0.860053,-0.153859,-0.552022,-0.338102,2.756877,0.613037,-0.364977,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,5.389384,-0.140043,-0.187617,-0.311532
13877,1.666223,2.321984,-0.860053,-0.153859,-0.552022,-0.338102,2.756877,0.761192,0.263830,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,5.389384,-0.140043,-0.187617,-0.311532
13878,1.666223,2.321984,-0.860053,-0.153859,-0.552022,-0.338102,2.756877,0.909347,-0.163759,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,-0.311532
13879,1.666223,2.321984,-0.860053,-0.153859,-0.552022,-0.338102,2.756877,1.057502,-0.440434,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,3.209945
13880,1.666223,2.321984,-0.860053,-0.153859,-0.552022,-0.338102,2.756877,1.205657,-0.314672,-0.310681,...,-0.216773,-0.109343,-0.194304,-0.203503,-0.239664,-0.163869,-0.185550,-0.140043,-0.187617,3.209945

In [89]:
num_time_steps = 20  # For example, 20 races in a season
num_features = X_train.shape[1]

# Initialize an empty list to store sequences
sequences = []

# Iterate through your data to create sequences
for sequence in range(0, len(X_train), num_time_steps):
    # Ensure the sequence is complete (has the required number of time steps)
    if (sequence + num_time_steps <= len(X_train)):
        sequences.append(X_train[sequence:sequence + num_time_steps])

# Convert the list of sequences into a numpy array
X_train_sequences = np.array(sequences)

print(X_train_sequences.shape)  # Should be [num_sequences, num_time_steps, num_features]

(694, 20, 98)

In [90]:
X_train_sequences

array([[[-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727,  3.20994485],
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        ...,
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727,  3.20994485],
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183]],

       [[-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
          5.32999984, -0.31153183],
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.60925681, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        ...,
        [-1.64732381, -1.41269479,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.41269479,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.41269479,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183]],

       [[-1.64732381, -1.41269479,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.41269479,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.41269479,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        ...,
        [-1.64732381, -1.21613277, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.21613277, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [-1.64732381, -1.21613277, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183]],

       ...,

       [[ 1.66622289,  1.73229746,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  1.73229746,  1.16271863, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  1.92885948, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        ...,
        [ 1.66622289,  1.92885948, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  1.92885948, -0.86005331, ..., -0.14004344,
         -0.18761727,  3.20994485],
        [ 1.66622289,  1.92885948, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183]],

       [[ 1.66622289,  1.92885948, -0.86005331, ..., -0.14004344,
         -0.18761727,  3.20994485],
        [ 1.66622289,  2.1254215 , -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.1254215 , -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        ...,
        [ 1.66622289,  2.1254215 , -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.1254215 , -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.1254215 , -0.86005331, ..., -0.14004344,
         -0.18761727,  3.20994485]],

       [[ 1.66622289,  2.1254215 , -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.32198351, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.32198351, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        ...,
        [ 1.66622289,  2.32198351, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.32198351, -0.86005331, ..., -0.14004344,
         -0.18761727, -0.31153183],
        [ 1.66622289,  2.32198351, -0.86005331, ..., -0.14004344,
         -0.18761727,  3.20994485]]])

In [91]:
y_train.shape

(13881,)

In [92]:
y_train_sequences = []
for i in range(0, len(y_train), 20):
    # Add the target of the last time step in each sequence
    if (i + 20 <= len(y_train)):
        y_train_sequences.append(y_train[i + 19])

y_train_sequences = np.array(y_train_sequences)

print(y_train_sequences.shape)

(694,)

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_sequences.shape[1], X_train_sequences.shape[2])))
model.add(LSTM(units=50))
model.add(Dense(units=1, activation='sigmoid'))  # For binary classification

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Use y_train_sequences, which is reshaped to match the sequences in X_train_sequences
model.fit(X_train_sequences, y_train_sequences, epochs=100, batch_size=32)

Epoch 1/100
22/22 [==============================] - 1s 7ms/step - loss: 0.5230 - accuracy: 0.8084
Epoch 2/100
22/22 [==============================] - 0s 7ms/step - loss: 0.2414 - accuracy: 0.9366
Epoch 3/100
22/22 [==============================] - 0s 7ms/step - loss: 0.1886 - accuracy: 0.9424
Epoch 4/100
22/22 [==============================] - 0s 7ms/step - loss: 0.1569 - accuracy: 0.9481
Epoch 5/100
22/22 [==============================] - 0s 7ms/step - loss: 0.1203 - accuracy: 0.9553
Epoch 6/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0933 - accuracy: 0.9669
Epoch 7/100
22/22 [==============================] - 0s 9ms/step - loss: 0.0628 - accuracy: 0.9827
Epoch 8/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0434 - accuracy: 0.9899
Epoch 9/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0367 - accuracy: 0.9942
Epoch 10/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0284 - accuracy: 0.9914
Epoch 11/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0159 - accuracy: 0.9986
Epoch 12/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0088 - accuracy: 1.0000
Epoch 13/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0057 - accuracy: 1.0000
Epoch 14/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 15/100
22/22 [==============================] - 0s 7ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 16/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 17/100
22/22 [==============================] - 0s 7ms/step - loss: 0.0022 - accuracy: 1.0000
Epoch 18/100
22/22 [==============================] - 0s 7ms/step - loss: 0.0018 - accuracy: 1.0000
Epoch 19/100
22/22 [==============================] - 0s 7ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 20/100
22/22 [==============================] - 0s 7ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 21/100
22/22 [==============================] - 0s 7ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 22/100
22/22 [==============================] - 0s 7ms/step - loss: 9.9619e-04 - accuracy: 1.0000
Epoch 23/100
22/22 [==============================] - 0s 7ms/step - loss: 8.7815e-04 - accuracy: 1.0000
Epoch 24/100
22/22 [==============================] - 0s 7ms/step - loss: 7.8522e-04 - accuracy: 1.0000
Epoch 25/100
22/22 [==============================] - 0s 7ms/step - loss: 7.0131e-04 - accuracy: 1.0000
Epoch 26/100
22/22 [==============================] - 0s 8ms/step - loss: 6.3283e-04 - accuracy: 1.0000
Epoch 27/100
22/22 [==============================] - 0s 7ms/step - loss: 5.7416e-04 - accuracy: 1.0000
Epoch 28/100
22/22 [==============================] - 0s 7ms/step - loss: 5.2382e-04 - accuracy: 1.0000
Epoch 29/100
22/22 [==============================] - 0s 7ms/step - loss: 4.8073e-04 - accuracy: 1.0000
Epoch 30/100
22/22 [==============================] - 0s 7ms/step - loss: 4.4038e-04 - accuracy: 1.0000
Epoch 31/100
22/22 [==============================] - 0s 7ms/step - loss: 4.0769e-04 - accuracy: 1.0000
Epoch 32/100
22/22 [==============================] - 0s 7ms/step - loss: 3.7828e-04 - accuracy: 1.0000
Epoch 33/100
22/22 [==============================] - 0s 7ms/step - loss: 3.5136e-04 - accuracy: 1.0000
Epoch 34/100
22/22 [==============================] - 0s 8ms/step - loss: 3.2810e-04 - accuracy: 1.0000
Epoch 35/100
22/22 [==============================] - 0s 8ms/step - loss: 3.0692e-04 - accuracy: 1.0000
Epoch 36/100
22/22 [==============================] - 0s 7ms/step - loss: 2.8712e-04 - accuracy: 1.0000
Epoch 37/100
22/22 [==============================] - 0s 7ms/step - loss: 2.7030e-04 - accuracy: 1.0000
Epoch 38/100
22/22 [==============================] - 0s 7ms/step - loss: 2.5440e-04 - accuracy: 1.0000
Epoch 39/100
22/22 [==============================] - 0s 7ms/step - loss: 2.4040e-04 - accuracy: 1.0000
Epoch 40/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2773e-04 - accuracy: 1.0000
Epoch 41/100
22/22 [==============================] - 0s 7ms/step - loss: 2.1472e-04 - accuracy: 1.0000
Epoch 42/100
22/22 [==============================] - 0s 7ms/step - loss: 2.0462e-04 - accuracy: 1.0000
Epoch 43/100
22/22 [==============================] - 0s 7ms/step - loss: 1.9370e-04 - accuracy: 1.0000
Epoch 44/100
22/22 [==============================] - 0s 7ms/step - loss: 1.8471e-04 - accuracy: 1.0000
Epoch 45/100
22/22 [==============================] - 0s 7ms/step - loss: 1.7651e-04 - accuracy: 1.0000
Epoch 46/100
22/22 [==============================] - 0s 7ms/step - loss: 1.6809e-04 - accuracy: 1.0000
Epoch 47/100
22/22 [==============================] - 0s 7ms/step - loss: 1.6110e-04 - accuracy: 1.0000
Epoch 48/100
22/22 [==============================] - 0s 7ms/step - loss: 1.5388e-04 - accuracy: 1.0000
Epoch 49/100
22/22 [==============================] - 0s 7ms/step - loss: 1.4763e-04 - accuracy: 1.0000
Epoch 50/100
22/22 [==============================] - 0s 7ms/step - loss: 1.4141e-04 - accuracy: 1.0000
Epoch 51/100
22/22 [==============================] - 0s 7ms/step - loss: 1.3585e-04 - accuracy: 1.0000
Epoch 52/100
22/22 [==============================] - 0s 7ms/step - loss: 1.3060e-04 - accuracy: 1.0000
Epoch 53/100
22/22 [==============================] - 0s 7ms/step - loss: 1.2573e-04 - accuracy: 1.0000
Epoch 54/100
22/22 [==============================] - 0s 7ms/step - loss: 1.2122e-04 - accuracy: 1.0000
Epoch 55/100
22/22 [==============================] - 0s 7ms/step - loss: 1.1664e-04 - accuracy: 1.0000
Epoch 56/100
22/22 [==============================] - 0s 7ms/step - loss: 1.1247e-04 - accuracy: 1.0000
Epoch 57/100
22/22 [==============================] - 0s 7ms/step - loss: 1.0861e-04 - accuracy: 1.0000
Epoch 58/100
22/22 [==============================] - 0s 7ms/step - loss: 1.0490e-04 - accuracy: 1.0000
Epoch 59/100
22/22 [==============================] - 0s 7ms/step - loss: 1.0132e-04 - accuracy: 1.0000
Epoch 60/100
22/22 [==============================] - 0s 7ms/step - loss: 9.8077e-05 - accuracy: 1.0000
Epoch 61/100
22/22 [==============================] - 0s 7ms/step - loss: 9.4827e-05 - accuracy: 1.0000
Epoch 62/100
22/22 [==============================] - 0s 7ms/step - loss: 9.1844e-05 - accuracy: 1.0000
Epoch 63/100
22/22 [==============================] - 0s 7ms/step - loss: 8.8904e-05 - accuracy: 1.0000
Epoch 64/100
22/22 [==============================] - 0s 7ms/step - loss: 8.6279e-05 - accuracy: 1.0000
Epoch 65/100
22/22 [==============================] - 0s 7ms/step - loss: 8.3572e-05 - accuracy: 1.0000
Epoch 66/100
22/22 [==============================] - 0s 7ms/step - loss: 8.1095e-05 - accuracy: 1.0000
Epoch 67/100
22/22 [==============================] - 0s 7ms/step - loss: 7.8650e-05 - accuracy: 1.0000
Epoch 68/100
22/22 [==============================] - 0s 7ms/step - loss: 7.6450e-05 - accuracy: 1.0000
Epoch 69/100
22/22 [==============================] - 0s 7ms/step - loss: 7.4227e-05 - accuracy: 1.0000
Epoch 70/100
22/22 [==============================] - 0s 7ms/step - loss: 7.2202e-05 - accuracy: 1.0000
Epoch 71/100
22/22 [==============================] - 0s 7ms/step - loss: 7.0167e-05 - accuracy: 1.0000
Epoch 72/100
22/22 [==============================] - 0s 7ms/step - loss: 6.8229e-05 - accuracy: 1.0000
Epoch 73/100
22/22 [==============================] - 0s 7ms/step - loss: 6.6408e-05 - accuracy: 1.0000
Epoch 74/100
22/22 [==============================] - 0s 7ms/step - loss: 6.4604e-05 - accuracy: 1.0000
Epoch 75/100
22/22 [==============================] - 0s 7ms/step - loss: 6.2920e-05 - accuracy: 1.0000
Epoch 76/100
22/22 [==============================] - 0s 7ms/step - loss: 6.1272e-05 - accuracy: 1.0000
Epoch 77/100
22/22 [==============================] - 0s 7ms/step - loss: 5.9702e-05 - accuracy: 1.0000
Epoch 78/100
22/22 [==============================] - 0s 7ms/step - loss: 5.8243e-05 - accuracy: 1.0000
Epoch 79/100
22/22 [==============================] - 0s 7ms/step - loss: 5.6737e-05 - accuracy: 1.0000
Epoch 80/100
22/22 [==============================] - 0s 7ms/step - loss: 5.5354e-05 - accuracy: 1.0000
Epoch 81/100
22/22 [==============================] - 0s 7ms/step - loss: 5.3979e-05 - accuracy: 1.0000
Epoch 82/100
22/22 [==============================] - 0s 7ms/step - loss: 5.2704e-05 - accuracy: 1.0000
Epoch 83/100
22/22 [==============================] - 0s 7ms/step - loss: 5.1411e-05 - accuracy: 1.0000
Epoch 84/100
22/22 [==============================] - 0s 7ms/step - loss: 5.0211e-05 - accuracy: 1.0000
Epoch 85/100
22/22 [==============================] - 0s 7ms/step - loss: 4.9012e-05 - accuracy: 1.0000
Epoch 86/100
22/22 [==============================] - 0s 8ms/step - loss: 4.7872e-05 - accuracy: 1.0000
Epoch 87/100
22/22 [==============================] - 0s 7ms/step - loss: 4.6760e-05 - accuracy: 1.0000
Epoch 88/100
22/22 [==============================] - 0s 7ms/step - loss: 4.5711e-05 - accuracy: 1.0000
Epoch 89/100
22/22 [==============================] - 0s 8ms/step - loss: 4.4655e-05 - accuracy: 1.0000
Epoch 90/100
22/22 [==============================] - 0s 7ms/step - loss: 4.3648e-05 - accuracy: 1.0000
Epoch 91/100
22/22 [==============================] - 0s 7ms/step - loss: 4.2706e-05 - accuracy: 1.0000
Epoch 92/100
22/22 [==============================] - 0s 7ms/step - loss: 4.1757e-05 - accuracy: 1.0000
Epoch 93/100
22/22 [==============================] - 0s 7ms/step - loss: 4.0873e-05 - accuracy: 1.0000
Epoch 94/100
22/22 [==============================] - 0s 7ms/step - loss: 3.9981e-05 - accuracy: 1.0000
Epoch 95/100
22/22 [==============================] - 0s 7ms/step - loss: 3.9119e-05 - accuracy: 1.0000
Epoch 96/100
22/22 [==============================] - 0s 7ms/step - loss: 3.8298e-05 - accuracy: 1.0000
Epoch 97/100
22/22 [==============================] - 0s 7ms/step - loss: 3.7501e-05 - accuracy: 1.0000
Epoch 98/100
22/22 [==============================] - 0s 7ms/step - loss: 3.6718e-05 - accuracy: 1.0000
Epoch 99/100
22/22 [==============================] - 0s 7ms/step - loss: 3.5981e-05 - accuracy: 1.0000
Epoch 100/100
22/22 [==============================] - 0s 7ms/step - loss: 3.5238e-05 - accuracy: 1.0000

In [93]:
validation = df2[df2.season >= 2019]

In [94]:
validation

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,grid,podium,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
13881,2019,1,True,False,False,False,False,hamilton,1,0,...,0,0,0,0,0,0,0,0,0,0
13882,2019,1,True,False,False,False,False,bottas,2,1,...,0,0,0,0,0,0,0,0,0,0
13883,2019,1,True,False,False,False,False,vettel,3,0,...,0,0,0,0,0,0,0,0,0,0
13884,2019,1,True,False,False,False,False,max_verstappen,4,0,...,0,0,1,0,0,0,0,0,0,0
13885,2019,1,True,False,False,False,False,leclerc,5,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14268,2019,21,True,False,False,False,False,giovinazzi,16,0,...,0,0,0,0,0,0,0,0,0,0
14269,2019,21,True,False,False,False,False,raikkonen,17,0,...,0,0,0,0,0,0,0,0,0,0
14270,2019,21,True,False,False,False,False,russell,18,0,...,0,0,0,0,0,0,0,0,0,1
14271,2019,21,True,False,False,False,False,kubica,19,0,...,0,0,0,0,0,0,0,0,0,1
14272,2019,21,True,False,False,False,False,bottas,20,0,...,0,0,0,0,0,0,0,0,0,0

In [96]:
from sklearn.preprocessing import StandardScaler

X_val = validation.drop(['driver', 'podium'], axis=1)  # Drop non-feature columns
y_val = validation.podium

# Scale X_val using the same scaler as for X_train
X_val = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns)

# Convert to numpy arrays and reshape
X_val = np.array(X_val)
X_val = X_val.reshape(X_val.shape[0], 1, X_val.shape[1])  # Reshape for LSTM input
y_val = y_val.to_numpy()  # Convert to numpy array if not already

# Create sequences
sequence_length = 20
X_val_sequences = []
y_val_sequences = []

for i in range(len(X_val) - sequence_length + 1):
    X_val_sequences.append(X_val[i:i+sequence_length, 0, :])
    y_val_sequences.append(y_val[i + sequence_length - 1])

X_val_sequences = np.array(X_val_sequences)
y_val_sequences = np.array(y_val_sequences)

In [97]:
print(X_val_sequences.shape)
print(y_val_sequences.shape)
print(X_train_sequences.shape)
print(y_train_sequences.shape)

(373, 20, 98)
(373,)
(694, 20, 98)
(694,)

In [98]:
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_sequences.shape[1], X_train_sequences.shape[2])))
model.add(Dropout(0.2))  # Adding dropout
model.add(LSTM(units=50))
model.add(Dropout(0.2))  # Adding dropout
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=10)  # Early stopping

# Assuming you have a validation dataset (X_val_sequences, y_val_sequences)
model.fit(X_train_sequences, y_train_sequences, epochs=100, batch_size=32, 
          validation_data=(X_val_sequences, y_val_sequences),
          callbacks=[early_stopping])

Epoch 1/100
22/22 [==============================] - 2s 22ms/step - loss: 0.5455 - accuracy: 0.7911 - val_loss: 0.3046 - val_accuracy: 0.9464
Epoch 2/100
22/22 [==============================] - 0s 8ms/step - loss: 0.2383 - accuracy: 0.9366 - val_loss: 0.2111 - val_accuracy: 0.9464
Epoch 3/100
22/22 [==============================] - 0s 9ms/step - loss: 0.1957 - accuracy: 0.9366 - val_loss: 0.2112 - val_accuracy: 0.9464
Epoch 4/100
22/22 [==============================] - 0s 9ms/step - loss: 0.1555 - accuracy: 0.9409 - val_loss: 0.2208 - val_accuracy: 0.9464
Epoch 5/100
22/22 [==============================] - 0s 9ms/step - loss: 0.1207 - accuracy: 0.9582 - val_loss: 0.2331 - val_accuracy: 0.9464
Epoch 6/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0956 - accuracy: 0.9697 - val_loss: 0.2588 - val_accuracy: 0.9464
Epoch 7/100
22/22 [==============================] - 0s 9ms/step - loss: 0.0721 - accuracy: 0.9755 - val_loss: 0.2819 - val_accuracy: 0.9464
Epoch 8/100
22/22 [==============================] - 0s 8ms/step - loss: 0.0461 - accuracy: 0.9885 - val_loss: 0.2776 - val_accuracy: 0.9464
Epoch 9/100
22/22 [==============================] - 0s 9ms/step - loss: 0.0319 - accuracy: 0.9928 - val_loss: 0.3191 - val_accuracy: 0.9383
Epoch 10/100
22/22 [==============================] - 0s 9ms/step - loss: 0.0214 - accuracy: 0.9986 - val_loss: 0.3716 - val_accuracy: 0.9383
Epoch 11/100
22/22 [==============================] - 0s 9ms/step - loss: 0.0306 - accuracy: 0.9914 - val_loss: 0.3055 - val_accuracy: 0.9303
Epoch 12/100
22/22 [==============================] - 0s 9ms/step - loss: 0.0303 - accuracy: 0.9914 - val_loss: 0.3083 - val_accuracy: 0.9088

In [99]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l1_l2

model = Sequential()

# Input LSTM layer
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_sequences.shape[1], X_train_sequences.shape[2])))
model.add(Dropout(0.2))  # Adding dropout

# Additional LSTM Layer with regularization
model.add(LSTM(units=50, return_sequences=True, kernel_regularizer=l1_l2(l1=1e-5, l2=1e-4), recurrent_regularizer=l1_l2(l1=1e-5, l2=1e-4)))
model.add(BatchNormalization())  # Adding batch normalization
model.add(Dropout(0.2))  # Adding dropout

# Another LSTM Layer
model.add(LSTM(units=50, return_sequences=False))
model.add(Dropout(0.2))  # Adding dropout

# Dense Layer
model.add(Dense(units=50, activation='relu'))
model.add(Dropout(0.2))  # Adding dropout

# Output layer
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Early stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=10)

# Fit the model
model.fit(X_train_sequences, y_train_sequences, epochs=100, batch_size=32, 
          validation_data=(X_val_sequences, y_val_sequences),
          callbacks=[early_stopping])

Epoch 1/100
22/22 [==============================] - 2s 32ms/step - loss: 0.4804 - accuracy: 0.8646 - val_loss: 0.4703 - val_accuracy: 0.9464
Epoch 2/100
22/22 [==============================] - 0s 14ms/step - loss: 0.2854 - accuracy: 0.9366 - val_loss: 0.3145 - val_accuracy: 0.9464
Epoch 3/100
22/22 [==============================] - 0s 14ms/step - loss: 0.2405 - accuracy: 0.9366 - val_loss: 0.2680 - val_accuracy: 0.9464
Epoch 4/100
22/22 [==============================] - 0s 15ms/step - loss: 0.2101 - accuracy: 0.9380 - val_loss: 0.2503 - val_accuracy: 0.9464
Epoch 5/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1904 - accuracy: 0.9366 - val_loss: 0.2471 - val_accuracy: 0.9464
Epoch 6/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1750 - accuracy: 0.9438 - val_loss: 0.2487 - val_accuracy: 0.9464
Epoch 7/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1349 - accuracy: 0.9510 - val_loss: 0.2584 - val_accuracy: 0.9464
Epoch 8/100
22/22 [==============================] - 0s 14ms/step - loss: 0.1079 - accuracy: 0.9597 - val_loss: 0.3035 - val_accuracy: 0.9464
Epoch 9/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0983 - accuracy: 0.9755 - val_loss: 0.2755 - val_accuracy: 0.9464
Epoch 10/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0921 - accuracy: 0.9741 - val_loss: 0.3324 - val_accuracy: 0.9464
Epoch 11/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0639 - accuracy: 0.9899 - val_loss: 0.3224 - val_accuracy: 0.9464
Epoch 12/100
22/22 [==============================] - 0s 15ms/step - loss: 0.0521 - accuracy: 0.9928 - val_loss: 0.3940 - val_accuracy: 0.9464
Epoch 13/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0531 - accuracy: 0.9899 - val_loss: 0.4106 - val_accuracy: 0.9464
Epoch 14/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0404 - accuracy: 0.9971 - val_loss: 0.4491 - val_accuracy: 0.9464
Epoch 15/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0418 - accuracy: 0.9942 - val_loss: 0.4308 - val_accuracy: 0.9464

In [100]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# Make predictions
y_val_pred = model.predict(X_val_sequences)

# Since your output layer uses a sigmoid activation, the predictions will be in the range [0, 1].
# Convert these to binary predictions.
y_val_pred_binary = (y_val_pred > 0.5).astype(int)

# Analyze predictions
print("Confusion Matrix:\n", confusion_matrix(y_val_sequences, y_val_pred_binary))
print("\nClassification Report:\n", classification_report(y_val_sequences, y_val_pred_binary))

# You can also visually check predictions vs actuals for some samples
for i in range(10):  # Just as an example, check first 10 samples
    print(f"Actual: {y_val_sequences[i]}, Predicted: {y_val_pred_binary[i][0]}")

12/12 [==============================] - 1s 3ms/step
Confusion Matrix:
 [[353   0]
 [ 20   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       353
           1       0.00      0.00      0.00        20

    accuracy                           0.95       373
   macro avg       0.47      0.50      0.49       373
weighted avg       0.90      0.95      0.92       373

Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 1, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0

/Users/shreyanshmac/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/shreyanshmac/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/shreyanshmac/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [101]:
from sklearn.utils.class_weight import compute_class_weight

# Compute class weights
class_weights = compute_class_weight('balanced', classes=np.unique(y_train_sequences), y=y_train_sequences)
class_weights_dict = dict(enumerate(class_weights))

# Train model with class weights
model.fit(X_train_sequences, y_train_sequences, class_weight=class_weights_dict, epochs=100, batch_size=32, 
          validation_data=(X_val_sequences, y_val_sequences),
          callbacks=[early_stopping])

Epoch 1/100
22/22 [==============================] - 2s 16ms/step - loss: 0.1777 - accuracy: 0.9856 - val_loss: 0.3734 - val_accuracy: 0.9437
Epoch 2/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0999 - accuracy: 0.9726 - val_loss: 0.6096 - val_accuracy: 0.8633
Epoch 3/100
22/22 [==============================] - 0s 15ms/step - loss: 0.2009 - accuracy: 0.9294 - val_loss: 0.6233 - val_accuracy: 0.8472
Epoch 4/100
22/22 [==============================] - 0s 14ms/step - loss: 0.2180 - accuracy: 0.9352 - val_loss: 0.4437 - val_accuracy: 0.8847
Epoch 5/100
22/22 [==============================] - 0s 14ms/step - loss: 0.1146 - accuracy: 0.9553 - val_loss: 0.5398 - val_accuracy: 0.8525
Epoch 6/100
22/22 [==============================] - 0s 14ms/step - loss: 0.1128 - accuracy: 0.9683 - val_loss: 0.4357 - val_accuracy: 0.9088
Epoch 7/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0574 - accuracy: 0.9914 - val_loss: 0.4389 - val_accuracy: 0.9088
Epoch 8/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0620 - accuracy: 0.9856 - val_loss: 0.4452 - val_accuracy: 0.9142
Epoch 9/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0468 - accuracy: 0.9928 - val_loss: 0.4324 - val_accuracy: 0.9169
Epoch 10/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0389 - accuracy: 0.9928 - val_loss: 0.4357 - val_accuracy: 0.9196
Epoch 11/100
22/22 [==============================] - 0s 14ms/step - loss: 0.0366 - accuracy: 0.9942 - val_loss: 0.4533 - val_accuracy: 0.9115

In [144]:
##############################################################################################################
const_stand_df = pd.read_csv('constructor_standings.csv')
driver_stand_df = pd.read_csv('driver_standings.csv')
quali_df = pd.read_csv('qualifying.csv')
races_df = pd.read_csv('races.csv')
results_df = pd.read_csv('results.csv')

In [145]:
const_stand_df

,season,round,constructor,constructor_points_after_race,constructor_wins_after_race,constructor_standings_pos_after_race,constructor_points,constructor_wins,constructor_standings_pos
0,1958,1,cooper,8.0,1,1,0.0,0.0,0.0
1,1958,1,ferrari,6.0,0,2,0.0,0.0,0.0
2,1958,1,maserati,3.0,0,3,0.0,0.0,0.0
3,1958,2,cooper,16.0,2,1,8.0,1.0,1.0
4,1958,2,ferrari,12.0,0,2,6.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...
12311,2019,21,toro_rosso,85.0,0,6,83.0,0.0,6.0
12312,2019,21,racing_point,73.0,0,7,67.0,0.0,7.0
12313,2019,21,alfa,57.0,0,8,57.0,0.0,8.0
12314,2019,21,haas,28.0,0,9,28.0,0.0,9.0
12315,2019,21,williams,1.0,0,10,1.0,0.0,10.0

In [146]:
#check for null values
const_stand_df = const_stand_df.drop(['constructor_points_after_race', 'constructor_wins_after_race','constructor_standings_pos_after_race' ],axis = 1)
const_stand_df

,season,round,constructor,constructor_points,constructor_wins,constructor_standings_pos
0,1958,1,cooper,0.0,0.0,0.0
1,1958,1,ferrari,0.0,0.0,0.0
2,1958,1,maserati,0.0,0.0,0.0
3,1958,2,cooper,8.0,1.0,1.0
4,1958,2,ferrari,6.0,0.0,2.0
...,...,...,...,...,...,...
12311,2019,21,toro_rosso,83.0,0.0,6.0
12312,2019,21,racing_point,67.0,0.0,7.0
12313,2019,21,alfa,57.0,0.0,8.0
12314,2019,21,haas,28.0,0.0,9.0
12315,2019,21,williams,1.0,0.0,10.0

In [147]:
# check for null values
const_stand_df.isnull().sum()

season                       0
round                        0
constructor                  0
constructor_points           0
constructor_wins             0
constructor_standings_pos    0
dtype: int64

In [148]:
races_df = races_df.drop(['url', 'lat', 'long'], axis=1)
races_df

      season  round    circuit_id      country        date
0       1950      1   silverstone           UK  1950-05-13
1       1950      2        monaco       Monaco  1950-05-21
2       1950      3  indianapolis          USA  1950-05-30
3       1950      4    bremgarten  Switzerland  1950-06-04
4       1950      5           spa      Belgium  1950-06-18
...      ...    ...           ...          ...         ...
1013    2019     17        suzuka        Japan  2019-10-13
1014    2019     18     rodriguez       Mexico  2019-10-27
1015    2019     19      americas          USA  2019-11-03
1016    2019     20    interlagos       Brazil  2019-11-17
1017    2019     21    yas_marina          UAE  2019-12-01

[1018 rows x 5 columns]

In [149]:
races_df.isnull().sum()

season        0
round         0
circuit_id    0
country       0
date          0
dtype: int64

In [150]:
results_df

,season,round,circuit_id,driver,date_of_birth,nationality,constructor,grid,time,status,points,podium,url
0,1950,1,silverstone,farina,1906-10-30,Italian,alfa,1,8003600.0,Finished,9.0,1,http://en.wikipedia.org/wiki/1950_British_Gran...
1,1950,1,silverstone,fagioli,1898-06-09,Italian,alfa,2,8006200.0,Finished,6.0,2,http://en.wikipedia.org/wiki/1950_British_Gran...
2,1950,1,silverstone,reg_parnell,1911-07-02,British,alfa,4,8055600.0,Finished,4.0,3,http://en.wikipedia.org/wiki/1950_British_Gran...
3,1950,1,silverstone,cabantous,1904-10-08,French,lago,6,NaN,+2 Laps,3.0,4,http://en.wikipedia.org/wiki/1950_British_Gran...
4,1950,1,silverstone,rosier,1905-11-05,French,lago,9,NaN,+2 Laps,2.0,5,http://en.wikipedia.org/wiki/1950_British_Gran...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24162,2019,21,yas_marina,giovinazzi,1993-12-14,Italian,alfa,16,NaN,+1 Lap,0.0,16,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24163,2019,21,yas_marina,russell,1998-02-15,British,williams,18,NaN,+1 Lap,0.0,17,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24164,2019,21,yas_marina,gasly,1996-02-07,French,toro_rosso,11,NaN,+2 Laps,0.0,18,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24165,2019,21,yas_marina,kubica,1984-12-07,Polish,williams,19,NaN,+2 Laps,0.0,19,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24166,2019,21,yas_marina,stroll,1998-10-29,Canadian,racing_point,12,NaN,Brakes,0.0,20,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...

In [151]:
results_df.isnull().sum()

season               0
round                0
circuit_id           0
driver               0
date_of_birth        0
nationality          0
constructor          0
grid                 0
time             17767
status               0
points              39
podium               0
url                  0
dtype: int64

In [152]:
#check distribution of points not using histogram
results_df.points.value_counts()
# results_df.points.hist()

points
0.0     17068
2.0      1020
4.0      1007
6.0       991
1.0       960
3.0       820
10.0      512
9.0       438
8.0       373
18.0      196
15.0      194
12.0      194
25.0      190
5.0       132
7.0         9
26.0        7
16.0        4
13.0        4
11.0        3
50.0        1
36.0        1
30.0        1
24.0        1
20.0        1
19.0        1
Name: count, dtype: int64

In [153]:
results_df['points'].fillna(0, inplace = True)
results_df

,season,round,circuit_id,driver,date_of_birth,nationality,constructor,grid,time,status,points,podium,url
0,1950,1,silverstone,farina,1906-10-30,Italian,alfa,1,8003600.0,Finished,9.0,1,http://en.wikipedia.org/wiki/1950_British_Gran...
1,1950,1,silverstone,fagioli,1898-06-09,Italian,alfa,2,8006200.0,Finished,6.0,2,http://en.wikipedia.org/wiki/1950_British_Gran...
2,1950,1,silverstone,reg_parnell,1911-07-02,British,alfa,4,8055600.0,Finished,4.0,3,http://en.wikipedia.org/wiki/1950_British_Gran...
3,1950,1,silverstone,cabantous,1904-10-08,French,lago,6,NaN,+2 Laps,3.0,4,http://en.wikipedia.org/wiki/1950_British_Gran...
4,1950,1,silverstone,rosier,1905-11-05,French,lago,9,NaN,+2 Laps,2.0,5,http://en.wikipedia.org/wiki/1950_British_Gran...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24162,2019,21,yas_marina,giovinazzi,1993-12-14,Italian,alfa,16,NaN,+1 Lap,0.0,16,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24163,2019,21,yas_marina,russell,1998-02-15,British,williams,18,NaN,+1 Lap,0.0,17,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24164,2019,21,yas_marina,gasly,1996-02-07,French,toro_rosso,11,NaN,+2 Laps,0.0,18,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24165,2019,21,yas_marina,kubica,1984-12-07,Polish,williams,19,NaN,+2 Laps,0.0,19,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24166,2019,21,yas_marina,stroll,1998-10-29,Canadian,racing_point,12,NaN,Brakes,0.0,20,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...

In [154]:
results_df.isnull().sum()

season               0
round                0
circuit_id           0
driver               0
date_of_birth        0
nationality          0
constructor          0
grid                 0
time             17767
status               0
points               0
podium               0
url                  0
dtype: int64

In [155]:
results_df = results_df.drop(['time'], axis=1)

In [156]:
results_df.isnull().sum()

season           0
round            0
circuit_id       0
driver           0
date_of_birth    0
nationality      0
constructor      0
grid             0
status           0
points           0
podium           0
url              0
dtype: int64

In [157]:
results_df

,season,round,circuit_id,driver,date_of_birth,nationality,constructor,grid,status,points,podium,url
0,1950,1,silverstone,farina,1906-10-30,Italian,alfa,1,Finished,9.0,1,http://en.wikipedia.org/wiki/1950_British_Gran...
1,1950,1,silverstone,fagioli,1898-06-09,Italian,alfa,2,Finished,6.0,2,http://en.wikipedia.org/wiki/1950_British_Gran...
2,1950,1,silverstone,reg_parnell,1911-07-02,British,alfa,4,Finished,4.0,3,http://en.wikipedia.org/wiki/1950_British_Gran...
3,1950,1,silverstone,cabantous,1904-10-08,French,lago,6,+2 Laps,3.0,4,http://en.wikipedia.org/wiki/1950_British_Gran...
4,1950,1,silverstone,rosier,1905-11-05,French,lago,9,+2 Laps,2.0,5,http://en.wikipedia.org/wiki/1950_British_Gran...
...,...,...,...,...,...,...,...,...,...,...,...,...
24162,2019,21,yas_marina,giovinazzi,1993-12-14,Italian,alfa,16,+1 Lap,0.0,16,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24163,2019,21,yas_marina,russell,1998-02-15,British,williams,18,+1 Lap,0.0,17,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24164,2019,21,yas_marina,gasly,1996-02-07,French,toro_rosso,11,+2 Laps,0.0,18,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24165,2019,21,yas_marina,kubica,1984-12-07,Polish,williams,19,+2 Laps,0.0,19,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...
24166,2019,21,yas_marina,stroll,1998-10-29,Canadian,racing_point,12,Brakes,0.0,20,https://en.wikipedia.org/wiki/2019_Abu_Dhabi_G...

In [158]:
### cleaning done: races, results, const_stand
quali_df

,grid_position,driver_name,car,qualifying_time,season,round
0,1,Keke Rosberg ROS,Williams Honda,1:34.526,1983,1
1,2,Alain Prost PRO,Renault,1:34.672,1983,1
2,3,Patrick Tambay TAM,Ferrari,1:34.758,1983,1
3,4,Nelson Piquet PIQ,Brabham BMW,1:35.114,1983,1
4,5,Derek Warwick WAR,Toleman Hart,1:35.206,1983,1
...,...,...,...,...,...,...
14554,16,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,1:38.114,2019,21
14555,17,Kimi RÃ¤ikkÃ¶nen RAI,Alfa Romeo Racing Ferrari,1:38.383,2019,21
14556,18,George Russell RUS,Williams Mercedes,1:38.717,2019,21
14557,19,Robert Kubica KUB,Williams Mercedes,1:39.236,2019,21
14558,20,Valtteri Bottas BOT,Mercedes,1:34.973,2019,21

In [161]:
quali_df.rename(columns = {'grid_position': 'grid'}, inplace = True)
print(quali_df.shape)

(14559, 6)

In [163]:
quali_df

,grid,driver_name,car,qualifying_time,season,round
0,1,Keke Rosberg ROS,Williams Honda,1:34.526,1983,1
1,2,Alain Prost PRO,Renault,1:34.672,1983,1
2,3,Patrick Tambay TAM,Ferrari,1:34.758,1983,1
3,4,Nelson Piquet PIQ,Brabham BMW,1:35.114,1983,1
4,5,Derek Warwick WAR,Toleman Hart,1:35.206,1983,1
...,...,...,...,...,...,...
14554,16,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,1:38.114,2019,21
14555,17,Kimi RÃ¤ikkÃ¶nen RAI,Alfa Romeo Racing Ferrari,1:38.383,2019,21
14556,18,George Russell RUS,Williams Mercedes,1:38.717,2019,21
14557,19,Robert Kubica KUB,Williams Mercedes,1:39.236,2019,21
14558,20,Valtteri Bottas BOT,Mercedes,1:34.973,2019,21

In [164]:
driver_stand_df

,season,round,driver,driver_points_after_race,driver_wins_after_race,driver_standings_pos_after_race,driver_points,driver_wins,driver_standings_pos
0,1950,1,farina,9.0,1,1,0.0,0.0,0.0
1,1950,1,fagioli,6.0,0,2,0.0,0.0,0.0
2,1950,1,reg_parnell,4.0,0,3,0.0,0.0,0.0
3,1950,1,cabantous,3.0,0,4,0.0,0.0,0.0
4,1950,1,rosier,2.0,0,5,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
26259,2019,21,kevin_magnussen,20.0,0,16,20.0,0.0,16.0
26260,2019,21,giovinazzi,14.0,0,17,14.0,0.0,17.0
26261,2019,21,grosjean,8.0,0,18,8.0,0.0,18.0
26262,2019,21,kubica,1.0,0,19,1.0,0.0,19.0
26263,2019,21,russell,0.0,0,20,0.0,0.0,20.0

In [165]:
driver_stand_df.drop(['driver_points_after_race', 'driver_wins_after_race', 'driver_standings_pos_after_race'] ,axis = 1, inplace = True)

print(driver_stand_df.shape)
driver_stand_df.head()

(26264, 6)

,season,round,driver,driver_points,driver_wins,driver_standings_pos
0,1950,1,farina,0.0,0.0,0.0
1,1950,1,fagioli,0.0,0.0,0.0
2,1950,1,reg_parnell,0.0,0.0,0.0
3,1950,1,cabantous,0.0,0.0,0.0
4,1950,1,rosier,0.0,0.0,0.0

In [166]:
quali_df

,grid,driver_name,car,qualifying_time,season,round
0,1,Keke Rosberg ROS,Williams Honda,1:34.526,1983,1
1,2,Alain Prost PRO,Renault,1:34.672,1983,1
2,3,Patrick Tambay TAM,Ferrari,1:34.758,1983,1
3,4,Nelson Piquet PIQ,Brabham BMW,1:35.114,1983,1
4,5,Derek Warwick WAR,Toleman Hart,1:35.206,1983,1
...,...,...,...,...,...,...
14554,16,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,1:38.114,2019,21
14555,17,Kimi RÃ¤ikkÃ¶nen RAI,Alfa Romeo Racing Ferrari,1:38.383,2019,21
14556,18,George Russell RUS,Williams Mercedes,1:38.717,2019,21
14557,19,Robert Kubica KUB,Williams Mercedes,1:39.236,2019,21
14558,20,Valtteri Bottas BOT,Mercedes,1:34.973,2019,21

In [168]:
results_df = results_df.drop(['url'], axis=1)
results_df

,season,round,circuit_id,driver,date_of_birth,nationality,constructor,grid,status,points,podium
0,1950,1,silverstone,farina,1906-10-30,Italian,alfa,1,Finished,9.0,1
1,1950,1,silverstone,fagioli,1898-06-09,Italian,alfa,2,Finished,6.0,2
2,1950,1,silverstone,reg_parnell,1911-07-02,British,alfa,4,Finished,4.0,3
3,1950,1,silverstone,cabantous,1904-10-08,French,lago,6,+2 Laps,3.0,4
4,1950,1,silverstone,rosier,1905-11-05,French,lago,9,+2 Laps,2.0,5
...,...,...,...,...,...,...,...,...,...,...,...
24162,2019,21,yas_marina,giovinazzi,1993-12-14,Italian,alfa,16,+1 Lap,0.0,16
24163,2019,21,yas_marina,russell,1998-02-15,British,williams,18,+1 Lap,0.0,17
24164,2019,21,yas_marina,gasly,1996-02-07,French,toro_rosso,11,+2 Laps,0.0,18
24165,2019,21,yas_marina,kubica,1984-12-07,Polish,williams,19,+2 Laps,0.0,19
24166,2019,21,yas_marina,stroll,1998-10-29,Canadian,racing_point,12,Brakes,0.0,20

In [170]:
# df1 = pd.merge(races, weather, how='inner', on=['season', 'round', 'circuit_id']).drop(['lat', 'long','country','weather'], axis = 1)
df2 = pd.merge(races_df, results_df, how='inner', on=['season', 'round', 'circuit_id']).drop(['points', 'status'], axis = 1)

df3 = pd.merge(df2, driver_stand_df, how='left', on=['season', 'round', 'driver']) 
df4 = pd.merge(df3, const_stand_df, how='left', on=['season', 'round', 'constructor']) #from 1958

final_df = pd.merge(df4, quali_df, how='inner', on=['season', 'round', 'grid']).drop(['driver_name', 'car'], axis = 1) #from 1983

In [171]:
final_df

,season,round,circuit_id,country,date,driver,date_of_birth,nationality,constructor,grid,podium,driver_points,driver_wins,driver_standings_pos,constructor_points,constructor_wins,constructor_standings_pos,qualifying_time
0,1983,1,jacarepagua,Brazil,1983-03-13,piquet,1952-08-17,Brazilian,brabham,4,1,0.0,0.0,0.0,0.0,0.0,0.0,1:35.114
1,1983,1,jacarepagua,Brazil,1983-03-13,lauda,1949-02-22,Austrian,mclaren,9,2,0.0,0.0,0.0,0.0,0.0,0.0,1:36.054
2,1983,1,jacarepagua,Brazil,1983-03-13,laffite,1943-11-21,French,williams,18,3,0.0,0.0,0.0,0.0,0.0,0.0,1:38.234
3,1983,1,jacarepagua,Brazil,1983-03-13,tambay,1949-06-25,French,ferrari,3,4,0.0,0.0,0.0,0.0,0.0,0.0,1:34.758
4,1983,1,jacarepagua,Brazil,1983-03-13,surer,1951-09-18,Swiss,arrows,20,5,0.0,0.0,0.0,0.0,0.0,0.0,1:38.468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14532,2019,21,yas_marina,UAE,2019-12-01,giovinazzi,1993-12-14,Italian,alfa,16,16,14.0,0.0,17.0,57.0,0.0,8.0,1:38.114
14533,2019,21,yas_marina,UAE,2019-12-01,russell,1998-02-15,British,williams,18,17,0.0,0.0,20.0,1.0,0.0,10.0,1:38.717
14534,2019,21,yas_marina,UAE,2019-12-01,gasly,1996-02-07,French,toro_rosso,11,18,95.0,0.0,6.0,83.0,0.0,6.0,1:37.089
14535,2019,21,yas_marina,UAE,2019-12-01,kubica,1984-12-07,Polish,williams,19,19,1.0,0.0,19.0,1.0,0.0,10.0,1:39.236
14536,2019,21,yas_marina,UAE,2019-12-01,stroll,1998-10-29,Canadian,racing_point,12,20,21.0,0.0,15.0,67.0,0.0,7.0,1:37.103

In [172]:
from dateutil.relativedelta import *

final_df['date'] = pd.to_datetime(final_df.date)
final_df['date_of_birth'] = pd.to_datetime(final_df.date_of_birth)
final_df['driver_age'] = final_df.apply(lambda x: relativedelta(x['date'], x['date_of_birth']).years, axis=1)
final_df.drop(['date', 'date_of_birth'], axis = 1, inplace = True)

In [173]:
# fill/drop nulls

for col in ['driver_points', 'driver_wins', 'driver_standings_pos', 'constructor_points', 
            'constructor_wins' , 'constructor_standings_pos']:
    final_df[col].fillna(0, inplace = True)
    final_df[col] = final_df[col].map(lambda x: int(x))
    
final_df.dropna(inplace = True )

In [174]:
# calculate difference in qualifying times

final_df['qualifying_time'] = final_df.qualifying_time.map(lambda x: 0 if str(x) == '00.000' 
                             else(float(str(x).split(':')[1]) + (60 * float(str(x).split(':')[0])) if x != 0 else 0))
final_df = final_df[final_df['qualifying_time'] != 0]
final_df.sort_values(['season', 'round', 'grid'], inplace = True)
final_df['qualifying_time_diff'] = final_df.groupby(['season', 'round']).qualifying_time.diff()
final_df['qualifying_time'] = final_df.groupby(['season', 'round']).qualifying_time_diff.cumsum().fillna(0)
final_df.drop('qualifying_time_diff', axis = 1, inplace = True)

/var/folders/lw/glss8t557pv__tkfgv16_7rm0000gn/T/ipykernel_2373/1733110307.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.sort_values(['season', 'round', 'grid'], inplace = True)
/var/folders/lw/glss8t557pv__tkfgv16_7rm0000gn/T/ipykernel_2373/1733110307.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['qualifying_time_diff'] = final_df.groupby(['season', 'round']).qualifying_time.diff()
/var/folders/lw/glss8t557pv__tkfgv16_7rm0000gn/T/ipykernel_2373/1733110307.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['qualifying_time'] = final_df.groupby(['season', 'round']).qualifying_time_diff.cumsum().fillna(0)
/var/folders/lw/glss8t557pv__tkfgv16_7rm0000gn/T/ipykernel_2373/1733110307.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop('qualifying_time_diff', axis = 1, inplace = True)

In [175]:
df_dum = pd.get_dummies(final_df, columns = ['circuit_id', 'nationality', 'constructor'] )

for col in df_dum.columns:
    if 'nationality' in col and df_dum[col].sum() < 140:
        df_dum.drop(col, axis = 1, inplace = True)
        
    elif 'constructor' in col and df_dum[col].sum() < 140:
        df_dum.drop(col, axis = 1, inplace = True)
        
    elif 'circuit_id' in col and df_dum[col].sum() < 70:
        df_dum.drop(col, axis = 1, inplace = True)
    
    else:
        pass

In [176]:
df_dum.shape

(14273, 96)

In [177]:
df_dum.to_csv('new_final_df.csv', index = False)

In [178]:
df_dum['podium'].unique()

array([15,  6,  4,  1,  7,  9, 23, 18,  2, 21, 26, 22, 16, 17, 25, 19, 20,
        3, 12,  5, 10, 11,  8, 24, 14, 13, 27])

In [179]:
df_dum

,season,round,country,driver,grid,podium,driver_points,driver_wins,driver_standings_pos,constructor_points,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
14,1983,1,Brazil,keke_rosberg,1,15,0,0,0,0,...,False,False,False,False,False,False,False,False,False,True
5,1983,1,Brazil,prost,2,6,0,0,0,0,...,False,False,False,True,False,False,False,False,False,False
3,1983,1,Brazil,tambay,3,4,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
0,1983,1,Brazil,piquet,4,1,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
6,1983,1,Brazil,warwick,5,7,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14532,2019,21,UAE,giovinazzi,16,16,14,0,17,57,...,False,False,False,False,False,False,False,False,False,False
14529,2019,21,UAE,raikkonen,17,13,43,0,12,57,...,False,False,False,False,False,False,False,False,False,False
14533,2019,21,UAE,russell,18,17,0,0,20,1,...,False,False,False,False,False,False,False,False,False,True
14535,2019,21,UAE,kubica,19,19,1,0,19,1,...,False,False,False,False,False,False,False,False,False,True
14520,2019,21,UAE,bottas,20,4,314,4,2,701,...,False,False,False,False,False,False,False,False,False,False

In [181]:
df_dum = df_dum.drop(['country'], axis = 1)

In [182]:
lstm_df = df_dum.copy()


train = lstm_df[lstm_df.season <2019]
X_train = train.drop(['driver', 'podium'], axis = 1)
y_train = train.podium

scaler = StandardScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)

In [183]:
def score_regression(model):
    score = 0
    for circuit in df[df.season == 2019]['round'].unique():

        test = df[(df.season == 2019) & (df['round'] == circuit)]
        X_test = test.drop(['driver', 'podium'], axis = 1)
        y_test = test.podium

        #scaling
        X_test = pd.DataFrame(scaler.transform(X_test), columns = X_test.columns)

        # make predictions
        prediction_df = pd.DataFrame(model.predict(X_test), columns = ['results'])
        prediction_df['podium'] = y_test.reset_index(drop = True)
        prediction_df['actual'] = prediction_df.podium.map(lambda x: 1 if x == 1 else 0)
        prediction_df.sort_values('results', ascending = True, inplace = True)
        prediction_df.reset_index(inplace = True, drop = True)
        prediction_df['predicted'] = prediction_df.index
        prediction_df['predicted'] = prediction_df.predicted.map(lambda x: 1 if x == 0 else 0)

        score += precision_score(prediction_df.actual, prediction_df.predicted)

    model_score = score / df[df.season == 2019]['round'].unique().max()
    return model_score

In [184]:
from sklearn.neural_network import MLPRegressor
comparison_dict ={'model':[],
                  'params': [],
                  'score': []}
params={'hidden_layer_sizes': [(80,20,40,5), (75,30,50,10,3)], 
        'activation': ['identity', 'relu','logistic', 'tanh',], 
        'solver': ['lbfgs','sgd', 'adam'], 
        'alpha': np.logspace(-4,1,20)} 

for hidden_layer_sizes in params['hidden_layer_sizes']:
    for activation in params['activation']:
        for solver in params['solver']:
            for alpha in params['alpha']:
                model_params = (hidden_layer_sizes, activation, solver, alpha )
                model = MLPRegressor(hidden_layer_sizes = hidden_layer_sizes,
                                      activation = activation, solver = solver, alpha = alpha, random_state = 1)
                model.fit(X_train, y_train)

                model_score = score_regression(model)

                comparison_dict['model'].append('nn_regressor')
                comparison_dict['params'].append(model_params)
                comparison_dict['score'].append(model_score)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- weather_cloudy
- weather_cold
- weather_dry
- weather_warm
- weather_wet